{% set name = "raxml-ng" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/amkozlov/raxml-ng/releases/download/{{ version }}/raxml-ng_v{{ version }}_source.zip
  sha256: 443e72a984a325ef32379f1fbfa4e90fb1d8928af6aefabc1e3653fa69afc6be

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - bison
    - flex
    - cmake
  host:
    - gmp
    - openmpi
  run:
    - openmpi

test:
  commands:
    - raxml-ng --version
    - raxml-ng-mpi --version # [not osx]

about:
   home: https://github.com/amkozlov/raxml-ng
   license: AGPL-3
   license_family: AGPL
   license_file: LICENSE.txt
   summary: "RAxML Next Generation: faster, easier-to-use and more flexible"

extra:
   container:
     # openmpi needs ssh client
     extended-base: true
   skip-lints:
     - uses_vcs_url
   identifiers:
     - doi:10.1093/bioinformatics/btz305
